site:
  about:
    siteName: "Rajmahendra's Blog"
    subtitle: 'I have no special talent. I am only passionately curious'
    siteDescription: 'Welcome to my website. You will learn and know more about Software technology (Mostly Java, Kotlin, Lightweight processes like Agile and Lean), Fermented food, Sustainable living,Gardening, Composting, Hyderoponic etc.'
    avatar: '/assets/media/icon.png'
  theme: 'FutureImperfect'
#  baseUrl: 'netlify'

posts:
  categories:
    - 'personal'
    - 'gardening'
    - 'coding'
    - 'fermentation'
  #permalink: ':category/:year/:monthName/:slug'
  permalink: 'blog/:year/:monthName/:slug'
  authors:
    - name: 'Rajmahendra'
      avatar: '/assets/media/icon.png'
      email: 'email@domain.tld'
  postPages:
    author: 'Rajmahendra'
    layout: index
    components:
      - type: pageContent
      - type: taxonomy
        taxonomyType: tags
      - type: taxonomy
        taxonomyType: categories

theme:
  social:
    facebook: 'rajmahednrar'
    twitter: 'rajmahendrar'
    instagram: 'rajmahendralive'
    github: 'rajmahendra'
    other:
      - label: 'linkedin'
        link: 'https://www.linkedin.com/in/rajmahendrar'
        icon: 'fa-linkedin'
      - label: 'youtube'
        link: 'https://www.youtube.com/user/rajmahendra'
        icon: 'fa-youtube'
      - label: 'codersrank'
        link: 'https://profile.codersrank.io/user/rajmahendra/'
        icon: 'fa-codersrank'
      - label: 'reddit'
        link: 'https://www.reddit.com/user/rrhegde'
        icon: 'fa-reddit'

  menu:
    - type: "wikiSections"
    - type: 'page'
      title: 'Blog'
      itemId: 'blog'
    - type: 'taxonomy'
      taxonomyType: 'categories'
    - type: 'taxonomy'
      taxonomyType: 'tags'
    - type: 'page'
      title: 'About'
      itemId: 'Rajmahendra'
    - type: "pages"
      atRoot: true
    - type: groupPages
      collectionType: pages
      collectionId: allPages
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

taxonomies:
  collectionArchives:
    - collectionType: 'posts'
#  collectionArchives:
#    - collectionType: 'blog'
#      archiveIndex: 50
  taxonomies:
    - key: tags
      single: false
      orderBy:
        - entryCount
    - key: categories
      single: false
      singleKey: category
      orderBy:
        - year
        - month
        - title
